version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "monthly"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      Microsoft:
        patterns:
          - "Microsoft.*"
      FluentEmail:
        patterns:
          - "jcamp.FluentEmail.*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry.*"
      xunit:
        patterns:
          - "xunit.*"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: nuget
    directory: /examples/minimal-api/src/AlbusKavaliro.TempMaiSe.Samples.Api
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /examples/minimal-api/test/AlbusKavaliro.TempMaiSe.Samples.Api.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/AlbusKavaliro.TempMaiSe.Mailer
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/AlbusKavaliro.TempMaiSe.Models
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/AlbusKavaliro.TempMaiSe.Tests
    schedule:
      interval: daily
