<Project>
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>TempMaiSe Team</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReleaseNotes>https://github.com/AlbusKavaliro/AlbusKavaliro/blob/main/CHANGELOG.md</PackageReleaseNotes>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <RepositoryUrl>https://github.com/AlbusKavaliro/TempMaiSe.git</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryBranch>main</RepositoryBranch>
    <RepositoryCommit>73f1cf558997666514b11f4ec55f2cc3c76fc264</RepositoryCommit>
    <Version>3.2.0-beta.1</Version>
  </PropertyGroup>

</Project>
